services:
  backend:
    container_name: backend
    image: karimarous/formation-backend:1.0.0   
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 100M
    environment:
    - DB_NAME=docker
    - DB_USER=docker
    - DB_PASSWORD=docker
    - DB_HOST=db
    depends_on:
      - db
    restart: always

  db:
    container_name: postgres
    image: postgres:14
    volumes:
      - ./volumes/db/config:/docker-entrypoint-initdb.d/
      - ./volumes/db/data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 100M
    restart: always

  frontend:
    container_name: frontend
    image: karimarous/formation-frontend:1.0.0
    ports:
      - "4200:4200"
    restart: always
    environment:
      - API_TARGET=https://bb.opsforall-formation.online
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
        reservations:
          cpus: '0.05'
          memory: 100M
      # depends_on:
      # - backend

  nginx:
    container_name: nginxproxy
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/logs:/var/log/nginx
      - ./volumes/certbot/www:/var/www/certbot
      - ./volumes/certbot/conf:/etc/letsencrypt
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 100M
    restart: always

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./volumes/certbot/www:/var/www/certbot
  #     - ./volumes/certbot/conf:/etc/letsencrypt
  #     - ./volumes/certbot/log:/var/log/letsencrypt:rw
  #   environment:
  #     - DOMAIN=t.opsforall-formation.online
  #     - EMAIL=karimmaroous@gmail.com

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./volumes/certbot/www:/var/www/certbot:rw
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/log:/var/log/letsencrypt
    entrypoint: >
      certbot certonly --webroot --webroot-path=/var/www/certbot --email karimmaroous@gmail.com --agree-tos --no-eff-email -d ff.opsforall-formation.online -d bb.opsforall-formation.online
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 100M
    restart: unless-stopped
